### ISSUE TITLE
Cannot install: SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 162-163: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by PacoH** [apetrynet/pyfilemail#8]
`pip3 install pyfilemail` and `python3 -m pip install pyfilemail` result in:

	ERROR: Command errored out with exit status 1:
		 command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_f/mth7tq5x4f3dpjkqs1z2y6mm0000gn/T/pip-install-vkdggvjz/pyfilemail/setup.py'"'"'; __file__='"'"'/private/var/folders/_f/mth7tq5x4f3dpjkqs1z2y6mm0000gn/T/pip-install-vkdggvjz/pyfilemail/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_f/mth7tq5x4f3dpjkqs1z2y6mm0000gn/T/pip-pip-egg-info-1rjiyrdm
			 cwd: /private/var/folders/_f/mth7tq5x4f3dpjkqs1z2y6mm0000gn/T/pip-install-vkdggvjz/pyfilemail/
		Complete output (7 lines):
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "/private/var/folders/_f/mth7tq5x4f3dpjkqs1z2y6mm0000gn/T/pip-install-vkdggvjz/pyfilemail/setup.py", line 4, in <module>
			import pyfilemail
		  File "/private/var/folders/_f/mth7tq5x4f3dpjkqs1z2y6mm0000gn/T/pip-install-vkdggvjz/pyfilemail/pyfilemail/__init__.py", line 112
				"""
		SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 162-163: truncated \UXXXXXXXX escape
		----------------------------------------
	ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

	virtualenv filemail
	source filemail
	source filemail/bin/activate
	pip install pyfilemail

Same result.

**Comment by apetrynet** [comment]
Hi @PacoH ! Thanks for your interest in pyfilemail. 
Unfortunately it does not support python3 as of now and I don't have a developers license to upgrade the code. So for the time being pyfilemail is discontinued.
The filemail-cli is a good replacement, but if you need python I suggest contacting filemail support so they know people are still using the library 😁
Thank you for filling the issue. Sorry I can't do much more ATM

**Comment by PacoH** [comment]
OK. Thanks. Do you mean this–[Filemail CLI 2\.57 \(2018\.07\.16\)](https://www.filemail.com/apidoc/FilemailLibs.aspx)? I tried it and it works.

**Comment by apetrynet** [comment]
Yes, that's the one. Glad it works for you. I'll close this ticket now if you don't mind?

**Comment by PacoH** [comment]
OK. I was just waiting for your answer.
